version: "3"
services:

  banco_mariadb:
    image: mariadb:latest
    container_name: banco_mariadb
    restart: unless-stopped
    tty: true
    volumes:
      - ./bd/mariadb:/var/lib/mysql/
      - ./dump:/docker-entrypoint-initdb.d/:ro
    env_file:
      - ./env/.env
    ports:
      - "3306:3306"
    networks:
      - app

  server:
    image: nginx:alpine
    container_name: server
    # restart: unless-stopped
    tty: true
    working_dir: /application
    volumes:
      - ./api/src:/application
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/logs
    ports:
      - "8000:80"
    depends_on:
      - banco_mariadb
    links:
      - banco_mariadb
    networks:
      - app

  composer:
    image: composer
    working_dir: /application
    volumes:
      - ./api/src:/application
    command: bash -c "composer install"
    networks:
      - app

  api:
    build: api
    container_name: api
    restart: unless-stopped
    tty: true
    depends_on:
      - banco_mariadb
    working_dir: /application
    volumes:
      - ./api/src:/application
      - ./env:/application/env

    networks:
      - app

  web:
    build:
      context: ./web/
      target: runner
    volumes:
      - ./web:/app
    command: npm run dev
    ports:
      - "80:3000"
    environment:
      NODE_ENV: development

networks:
  app:
    driver: bridge

volumes:
  database:
    driver: local
